export const places = ['Abastumani', 'Adigeni', 'Adjarian Wine House', 'Agara', 'Akhaldaba', 'Akhali Shuamta Monastery', 'Akhalkalaki',
    'Akhaltsikhe', 'Akhalubani', 'Akhasheni', 'Akhmeta', 'Alaverdi Monastery', 'Algeti National Park',
    'Algeti Reservoir', 'Alismereti', 'Almasiani', 'Ambrolauri', 'Amusement Park Tsitsinatela', 'Anaklia', 'Ananuri',
    'Aragvi Adventure Center', 'Arashenda', 'Argo Cable Car Batumi', 'Arjevan-Sarvani', 'Arsha', 'Artana', 'Aspindza',
    'Asureti', 'Ateni Sioni', 'Atsana', 'Babaneuri', 'Baghdati', 'Bagrati Cathedral', 'Bakhmaro', 'Bakuriani',
    'Bandza', 'Barisakho', 'Batumi', 'Batumi Airport', 'Batumi Botanical Garden', 'Batumi Central Station',
    'Batumi Dolphinarium', 'Batumi, Black Sea Jazz', 'Bazaleti Lake', 'Beshumi', 'Betania Monastery', 'Biisi',
    'Birtvisi', 'Bobnevi', 'Bodbe Monastery', 'Bolnisi', 'Bolnisi Sioni', 'Borjomi', 'Botanical Garden Tbilisi',
    'Bulachauri', 'Buriani', 'Castle of Rukhi', 'Central Bus Station Ortachala', 'Chakvi', 'Chardakhi',
    'Chateau Chapiteau', 'Chateau Iveri', 'Chateau Mukhrani Winery', 'Chiatura', 'Chobiskhevi', 'Chokhatauri',
    'Chorvila', 'Chronicle of Georgia', 'Chumlaki', 'Dadiani Palace', 'Dariali', 'Dashbashi Canyon',
    'David Gareji Monasteri', 'Dedoplistsqaro', 'Didgori Battle Memorial', 'Dmanisi', 'Dmanisi Museum-Reserve',
    'Duisi', 'Dusheti', 'Dzegvi', 'Dzveli Kanda', 'Dzveli Shuamta Monastery', 'Enguri Dam', 'Ergneti',
    'Ertatsminda Cathedral', 'Ethnographic Museum Borjgalo', 'Etseri', 'Forest Sabaduri', 'Friendship Monument',
    'Gamarjveba', 'Gardabani', 'Gegelidzeebi', 'Geguti Palace', 'Gelati Monastery', 'Georgia–Russia border', 'Ghebi',
    'Glola', 'Gomarduli', 'Gomi', 'Gomismta', 'Gonio', 'Gonio Cross', 'Gonio Fortress', 'Gori', 'Graneli Winery',
    'Green Lake', 'Gremi', 'Grigoleti', 'Gudauri', 'Gulelebi', 'Gurjaani', 'Gvara Fortress', 'Gveleti',
    'Holy Trinity Cathedral of Tbilisi (Sameba)', 'Igoeti', 'Ikalto', 'Ilia Lake', 'Jakhunderi', 'Jandari Lake',
    'Javakhishvili Wine Cellar', 'Jewelberry Shuaguli Glamping', 'Jokolo', 'Jvari', 'Jvari (town)', 'Kachreti',
    'Kakabeti', 'Kakliani', 'Kapnistavi', 'Kaprovani', 'Karaleti', 'Kardenakhi', 'Kareli', 'Kaspi', 'Katskhi Pillar',
    'Kavtiskhevi', 'Kazreti', 'Keda', 'Khala', 'Khani', 'Kharagauli', 'Khashmi', 'Khashuri', 'Khertvisi Fortress',
    'Khobi', 'Khobi Convent', 'Khoni', 'Khulo', 'Khvanchkara', 'Kiketi', 'Kinchkha Waterfall', 'Kintsvisi Monastery',
    'Kisiskhevi', 'Kitokhi', 'Kobuleti', 'Kojori', 'Kokhi', 'Kokotauri', 'Kolagiri', 'Kolkheti National Park',
    'Kondoli', 'Ksani', 'Ksovrisi Church', 'Kulevi', 'Kumisi Lake', 'Kutaisi', 'Kutaisi Airport', 'Kvabiskhevi',
    'Kvareli', 'Kvariati', 'Kvashta', 'Kvatakhevi', 'Kveda Chkhutuneti', 'Kveda Pona', 'Kvemo Alvani', 'Kvemo Magharo',
    'Kvemo Mleta', 'Kvemo Teleti', 'Kvibisi', 'Kvishkheti', 'Kvitkiristskaro St. George Church & Petre Tower',
    'Lagodekhi', 'Lailashi', 'Lanchkhuti', 'Lapankuri', 'Ledzadzame', 'Lentekhi', 'Likani', 'Lilo Mall', 'Lopota Lake',
    'Machakhela National Park', 'Madatapa Lake', 'Magraneti', 'Makhinjauri', 'Makhuntseti Waterfall', 'Maltakva',
    'Mamkoda', 'Manavi', 'Manglisi', 'Marneuli', 'Martkopi monastery', 'Martvili', 'Martvili Canyon', 'Mazeri',
    'Menji Sanatorium', 'Merisi', 'Mestia', 'Mgvimevi Monastery', 'Miniature Park', 'Misaktsieli', 'Mlashe',
    'Motsameta Monastery', 'Mravaltskaro Reservoir', 'Mskhaldidi', 'Mtatsminda Park', 'Mtirala National Park',
    'Mtskheta', 'Mtsvane Kontskhi', 'Mtsvane Monastery', 'Mukhatskaro', 'Mukhrani', 'Mukhuri', 'Mukuzani',
    'Museum of Illusions', 'Mutso', 'Mzovreti Monastery', 'Nakalakevi', 'Nakhshirghele', 'Napareuli', 'Nardevani',
    'Narikala Fortress', 'Natakhtari', 'Navazi', 'Navenakhevi Cave', 'Nekresi', 'Niko Pirosrmani museum',
    'Nikortsminda', 'Ninotsminda', 'Ninotsminda (Kakheti)', 'Nokalakevi', 'Norio', 'Nukriani', 'Okami',
    'Okatse Canyon', 'Omalo', 'Oni', 'Orbeti', 'Ozurgeti', 'Paravani Lake', 'Pasanauri', 'Patara Khurvaleti',
    'Patara Zanavi', 'Petra Fortress', 'Pichkhovani', 'Poka', 'Poka St. Nino Monastery', 'Poti', 'Prometheus Cave',
    'Pshaveli', 'Rabati Castle', 'Red Bridge Customs Post', 'Rioni Railway Station', 'Rkoni Monastery', 'Ruispiri',
    'Rustavi', 'Saakadze', 'Sachkhere', 'Sadakhlo', 'Sagarejo', 'Sagholasheni', 'Saghrasheni', 'Saguramo', 'Sairme',
    'Salkhino Dadiani Summer Residence', 'Sameba Mountain', 'Samshvilde', 'Samtavisi Cathedral', 'Samtavro Monastery',
    'Samtredia', 'Sarpi', 'Sartichala', 'Sasadilo', 'Sataplia', 'Satskhenisi', 'Senaki', 'Sepe', 'Shashiani',
    'Shatili', 'Shekvetili', 'Shekvetili Dendrological Park', 'Shekvetili Music Park', 'Shervashidze Wine Cellar',
    'Shilda', 'Shiomghvime Monastery', 'Shiraki Military Airfield', 'Shkhepi Fortress', 'Shuakhevi', 'Shulaveri',
    'Shumi winery', 'Signagi', 'Sioni Reservoir', 'Sno', 'Stalin Museum', 'Stepantsminda(Kazbegi)', 'Surami',
    'Svetitskhoveli Cathedral', 'Tabakhmela', 'Tbilisi', 'Tbilisi Airport', 'Tbilisi Open Air Museum of Ethnography',
    'Tbilisi Railway Station', 'Telavi', 'Temple of Saint Seraphim of Sarov', 'Terjola', 'Tetra Cave', 'Tetritsqaro',
    'Tianeti', 'Tibaani', 'Tkhilnari', 'Tkibuli', 'Tkviavi', 'Tmogvi Fortress', 'Tsageri', 'Tsaghveri',
    'Tsaishi Cathedral', 'Tsakhi', 'Tsalka', 'Tsavkisi', 'Tserovani', 'Tsikhisdziri', 'Tsinandali', 'Tsinsvla',
    'Tsintskaro', 'Tsitelmta', 'Tskaltbila', 'Tskaltubo', 'Tskhrajvari', 'Tskhvarichamia', 'Tskneti', 'Tsnori',
    'Tsodoreti', 'Turtle Lake', 'Udabno', 'Ujarma', 'Underground Printing House Museum', 'Uplistsikhe', 'Uravi',
    'Ureki', 'Vachnadziani', 'Vani', 'Vanis Kvabebi', 'Vardzia', 'Varjanisi', 'Vartsikhe', 'Vashlovani National Park',
    'Vashlovani Tower (Salkhino)', 'Vaziani Winery', 'Vazisubani', 'Vejini', 'Velistsikhe',
    'Vladimir Mayakovski House Museum', 'Waterfall Mirveti', 'Waterfall of the Apostle Andrew the First-Called',
    'Winery Khareba', 'Zanavi', 'Zeda Sazano', 'Zedazeni Monastery', 'Zegani', 'Zekari', 'Zemo Alvani', 'Zemo Mleta',
    'Zemo-Machkhaani', 'Zestaponi', 'Zhinvali Water Reservoir', 'Zugdidi', 'Zvari Church']

export default places